Removed dependence from daspanel/alpine-base.

diff --git a/rootfs/etc/cont-init.d/40-00-php71-fpm b/rootfs/etc/cont-init.d/40-00-php71-fpm
--- a/rootfs/etc/cont-init.d/40-00-php71-fpm
+++ b/rootfs/etc/cont-init.d/40-00-php71-fpm
@@ -1,5 +1,6 @@
 #!/usr/bin/with-contenv sh
 
+# Set the type of this container
 export DASPANEL_CONTAINER_TYPE="daspanel-services"
 printf $DASPANEL_CONTAINER_TYPE > /var/run/s6/container_environment/DASPANEL_CONTAINER_TYPE
 
@@ -11,7 +12,7 @@ fi
 
 case "$DASPANEL_WAIT_FOR_API" in
     YES|yes|Yes)
-        echo "[DASPANEL] Waiting 60 seconds for API: $0" >&2
+        echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Waiting 60 seconds for API: $0" >&2
         /opt/daspanel/bin/wait-for-api -t 60 $DASPANEL_SYS_APISERVER/info/status
         result=$?
         if [ ! $result -eq 0 ] ; then
@@ -25,26 +26,16 @@ case "$DASPANEL_WAIT_FOR_API" in
         ;;
 esac
 
-if [ ! -d "/etc/caddy" ]; then
-    mkdir -p /etc/caddy
+# Get system configs from API server and set env variables
+SYSCFG=$(wget -O- --header=Content-Type:application/json --header="Authorization: $DASPANEL_SYS_APIKEY" "$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID")
+result=$?
+if [ ! $result -eq 0 ] ; then
+    echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Unable to get tenant configuration from API server: $0" >&2
+    exit 1
 fi
+export DASPANEL_SYS_HOSTNAME=`echo $SYSCFG | /opt/daspanel/bin/jq -r '.sys.hostname'`
 
-log() {
-  if [[ "$@" ]]; then echo "[`date +'%Y-%m-%d %T'`] $@";
-  else echo; fi
-}
-
-if [ ! -d "/opt/daspanel/log/$DASPANEL_SYS_UUID/caddy" ]; then
-	mkdir -p /opt/daspanel/log/$DASPANEL_SYS_UUID/caddy
-fi
-
-# Configure caddy
-/opt/daspanel/bin/gomplate -d cfg=$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID \
-    -H "cfg=Authorization: $DASPANEL_SYS_APIKEY" \
-    < /opt/daspanel/conf-templates/daspanel-services/caddy/caddyfile.tmpl \
-    > /etc/caddy/caddyfile
-
-# secure daspanel
-chown -R daspanel:daspanel /opt/daspanel/data
-chown -R daspanel:daspanel /opt/daspanel/log
+chmod ugo+x /opt/daspanel/bin/${DASPANEL_CONTAINER_TYPE}/genconfig
+sync
+/opt/daspanel/bin/${DASPANEL_CONTAINER_TYPE}/genconfig
 
